spring:
  datasource:
    url: jdbc:mysql://localhost:3306/os_exercise?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 123123