spring:
  datasource:
    url: jdbc:mysql://ip:3306/os_exercise?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username:
    password:

mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档访问 配置用户名和密码
knife4j:
  basic:
    enable: true
    username:
    password:
logging:
  level:
    org.springframework.data.redis: info

