/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableCustom: typeof import('./components/TableCustom.vue')['default']
    TableDetail: typeof import('./components/TableDetail.vue')['default']
    TableEdit: typeof import('./components/TableEdit.vue')['default']
    TableSearch: typeof import('./components/TableSearch.vue')['default']
  }
}
